require('dotenv').config();
const express=require('express'),path=require('path'),nodemailer=require('nodemailer');
const app=express(),PORT=process.env.PORT||3000,KEY=process.env.ALCHEMY_API_KEY,NETWORK=process.env.ALCHEMY_NETWORK||'eth-mainnet',TIMEOUT=10000;
app.use(express.json());app.use(express.static(path.join(__dirname,'..')));
async function request(url,options={}){const r=await fetch(url,{...options,signal:AbortSignal.timeout(TIMEOUT)}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||d.error||`Provider HTTP ${r.status}`);return d;}
async function rpc(method,params){if(!KEY)throw new Error('Alchemy API key is required for live monitoring.');const d=await request(`https://${NETWORK}.g.alchemy.com/v2/${KEY}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})});if(d.error)throw new Error(d.error.message||'Alchemy request failed');return d.result;}
function smtpConfigured(){return !!(process.env.SMTP_HOST&&process.env.SMTP_USER&&process.env.SMTP_PASS&&process.env.ALERT_EMAIL_TO);}
function mailer(){return nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||465),secure:String(process.env.SMTP_SECURE||'true')==='true',auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}});}
function normalise(t){return {blockNum:t.blockNum||t.block||t.block_number,hash:t.hash,from:t.from?.hash||t.from,to:t.to?.hash||t.to,value:Number(t.value||0),asset:(t.asset||'ETH').toUpperCase(),category:t.category||'transaction',contractAddress:t.rawContract?.address||t.token?.address||null,timestamp:t.metadata?.blockTimestamp||t.timestamp||null};}
async function getTransfers(address,liveOnly=false){if(KEY){const base={fromBlock:'0x0',toBlock:'latest',category:['external','internal','erc20'],withMetadata:true,maxCount:'0x64',order:'desc'},[a,b]=await Promise.all([rpc('alchemy_getAssetTransfers',[{...base,fromAddress:address}]),rpc('alchemy_getAssetTransfers',[{...base,toAddress:address}])]),seen=new Set(),transfers=[...(a.transfers||[]),...(b.transfers||[])].map(normalise).filter(t=>{const id=`${t.hash}|${t.from}|${t.to}|${t.category}|${t.value}`;if(seen.has(id))return false;seen.add(id);return true;}).sort((x,y)=>timeMs(y.timestamp)-timeMs(x.timestamp));return {provider:'Alchemy',transfers};}if(liveOnly)throw new Error('Live monitoring requires a free Alchemy API key. Add ALCHEMY_API_KEY to .env.');const d=await request(`https://eth.blockscout.com/api/v2/addresses/${address}/transactions`,{headers:{accept:'application/json'}});return {provider:'Blockscout',transfers:(Array.isArray(d.items)?d.items:[]).slice(0,100).map(normalise)};}
function scoreTransfer(t){const asset=String(t.asset||'').toUpperCase(),value=Number(t.value||0);if(asset==='ETH'&&value>=10)return {riskScore:85,reason:'Large ETH transfer (≥ 10 ETH)'};if(['USDC','USDT','DAI'].includes(asset)&&value>=10000)return {riskScore:85,reason:`Large stablecoin transfer (≥ 10,000 ${asset})`};return {riskScore:0,reason:null};}
const STABLES={USDC:{address:'0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',decimals:6},USDT:{address:'0xdac17f958d2ee523a2206206994597c13d831ec7',decimals:6},DAI:{address:'0x6b175474e89094c44da98b954eedeac495271d0f',decimals:18}},TRANSFER='0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',PATTERN_WINDOW=10*60*1000;
const walletActivity=new Map(),riskCache=new Map();
function topicAddress(topic){return `0x${topic.slice(-40)}`;}
function timeMs(value){if(!value)return 0;const numeric=Number(value);if(Number.isFinite(numeric)&&numeric>0)return numeric<1e12?numeric*1000:numeric;const parsed=Date.parse(value);return Number.isFinite(parsed)?parsed:0;}
function riskLevel(score){return score>=90?'CRITICAL':score>=75?'HIGH':score>=50?'MEDIUM':'LOW';}
function amountPoints(asset,value){asset=String(asset||'').toUpperCase();value=Number(value||0);if(asset==='ETH')return value>=100?25:value>=50?20:value>=10?12:0;if(['USDC','USDT','DAI'].includes(asset))return value>=100000?25:value>=50000?20:value>=10000?12:0;return 0;}
function isRiskEligible(t){const asset=String(t.asset||'').toUpperCase(),category=String(t.category||'').toLowerCase();if(asset==='ETH')return ['external','internal','transaction'].includes(category);const stable=STABLES[asset],contract=String(t.contractAddress||'').toLowerCase();return Boolean(stable&&contract===stable.address);}
function transferDirection(address,t){const target=String(address).toLowerCase(),from=String(t.from||'').toLowerCase(),to=String(t.to||'').toLowerCase();if(from===target&&to===target)return 'self';if(to===target)return 'incoming';if(from===target)return 'outgoing';return 'related';}
function densestWindow(transfers,windowMs=PATTERN_WINDOW){const ordered=transfers.filter(t=>timeMs(t.timestamp)).sort((a,b)=>timeMs(a.timestamp)-timeMs(b.timestamp));let best=[];for(let left=0,right=0;right<ordered.length;right++){while(timeMs(ordered[right].timestamp)-timeMs(ordered[left].timestamp)>windowMs)left++;const candidate=ordered.slice(left,right+1);if(candidate.length>best.length)best=candidate;}return best;}
function analyseWallet(address,transfers){
  const target=address.toLowerCase(),enriched=transfers.map(t=>({...t,direction:transferDirection(target,t)})),eligible=enriched.filter(isRiskEligible);
  const incoming=eligible.filter(t=>t.direction==='incoming'),outgoing=eligible.filter(t=>t.direction==='outgoing'),allIncoming=enriched.filter(t=>t.direction==='incoming'),allOutgoing=enriched.filter(t=>t.direction==='outgoing'),counterpartyCounts=new Map(),totalsByAsset={};
  for(const t of enriched){const cp=(t.direction==='incoming'?t.from:t.direction==='outgoing'?t.to:null)?.toLowerCase();if(cp)counterpartyCounts.set(cp,(counterpartyCounts.get(cp)||0)+1);const asset=t.asset||'UNKNOWN';if(!totalsByAsset[asset])totalsByAsset[asset]={incoming:0,outgoing:0};if(t.direction==='incoming')totalsByAsset[asset].incoming+=Number(t.value||0);if(t.direction==='outgoing')totalsByAsset[asset].outgoing+=Number(t.value||0);}
  const window=densestWindow(eligible),windowIncoming=window.filter(t=>t.direction==='incoming'),windowOutgoing=window.filter(t=>t.direction==='outgoing'),windowSources=new Set(windowIncoming.map(t=>String(t.from).toLowerCase())),windowRecipients=new Set(windowOutgoing.map(t=>String(t.to).toLowerCase()));
  const rapid=window.length>=3,burst=window.length>=6,fanOut=windowOutgoing.length>=3&&windowRecipients.size>=3,fanIn=windowIncoming.length>=3&&windowSources.size>=3;
  let immediateForward=false;for(const received of incoming){const receivedAt=timeMs(received.timestamp);if(!receivedAt)continue;if(outgoing.some(sent=>{const sentAt=timeMs(sent.timestamp);return sentAt>=receivedAt&&sentAt-receivedAt<=15*60*1000;})){immediateForward=true;break;}}
  const eligibleCounterparties=new Map();for(const t of eligible){const cp=(t.direction==='incoming'?t.from:t.direction==='outgoing'?t.to:null)?.toLowerCase();if(cp)eligibleCounterparties.set(cp,(eligibleCounterparties.get(cp)||0)+1);}const maxAmountPoints=Math.max(0,...eligible.map(t=>amountPoints(t.asset,t.value))),dominantCount=Math.max(0,...eligibleCounterparties.values()),concentrated=eligible.length>=8&&dominantCount/eligible.length>=.6;
  let score=0;const signals=[];const add=(key,label,points,detail)=>{score+=points;signals.push({key,label,points,detail});};
  if(maxAmountPoints)add('large_value','Large-value activity',maxAmountPoints,'At least one transfer crossed the configured ETH or stablecoin review threshold.');
  if(rapid)add('rapid_movement','Rapid movement',18,`${window.length} transfers occurred inside the busiest 10-minute window.`);
  if(burst)add('sustained_burst','Sustained burst',12,'Six or more transfers occurred inside one 10-minute window.');
  if(fanOut)add('fan_out','Fan-out',22,`${windowRecipients.size} distinct recipients appeared in the busiest 10-minute window.`);
  if(fanIn)add('fan_in','Fan-in',18,`${windowSources.size} distinct sources appeared in the busiest 10-minute window.`);
  if(immediateForward)add('immediate_forwarding','Immediate forwarding',20,'Outgoing activity followed incoming activity within 15 minutes.');
  if(concentrated)add('counterparty_concentration','Counterparty concentration',8,`${Math.round(dominantCount/eligible.length*100)}% of risk-eligible transfers involve one counterparty.`);
  if(rapid&&(fanOut||fanIn)&&immediateForward)add('compounded_pattern','Compounded flow pattern',15,'Velocity, network dispersion and forwarding signals overlap.');
  score=Math.min(99,score);
  if(!signals.length)signals.push({key:'no_strong_pattern',label:'No strong pattern detected',points:0,detail:'The retrieved activity did not match the current review rules.'});
  return {score,level:riskLevel(score),signals,summary:{transferCount:enriched.length,riskEligibleTransferCount:eligible.length,incomingCount:allIncoming.length,outgoingCount:allOutgoing.length,uniqueCounterparties:counterpartyCounts.size,busiestWindowCount:window.length,totalsByAsset},transfers:enriched};
}
function graphForWallet(address,transfers){
  const target=address.toLowerCase(),groups=new Map(),eligible=transfers.filter(isRiskEligible),graphTransfers=eligible.length?eligible:transfers.filter(t=>Number(t.value||0)>0);
  for(const t of graphTransfers){const direction=transferDirection(target,t);if(!['incoming','outgoing'].includes(direction))continue;const cp=String(direction==='incoming'?t.from:t.to).toLowerCase();if(!groups.has(cp))groups.set(cp,{address:cp,incoming:[],outgoing:[],count:0,total:0});const group=groups.get(cp);group[direction].push(t);group.count++;group.total+=Math.abs(Number(t.value||0));}
  const selected=[...groups.values()].sort((a,b)=>b.count-a.count||b.total-a.total).slice(0,12),nodes=[{id:target,label:'Investigated wallet',type:'subject',address:target,side:'center'}],edges=[];
  for(const group of selected){const side=group.incoming.length&&group.outgoing.length?'mixed':group.incoming.length?'incoming':'outgoing';nodes.push({id:group.address,label:group.address,type:'wallet',address:group.address,side,count:group.count});for(const direction of ['incoming','outgoing']){const rows=group[direction];if(!rows.length)continue;const strongest=rows.reduce((best,t)=>Number(t.value||0)>Number(best.value||0)?t:best,rows[0]);edges.push({id:`${group.address}:${direction}`,source:direction==='incoming'?group.address:target,target:direction==='incoming'?target:group.address,direction,count:rows.length,label:`${rows.length} tx · ${Number(strongest.value||0).toFixed(2)} ${strongest.asset}`});}}
  return {nodes,edges,truncated:groups.size>selected.length,totalCounterparties:groups.size};
}
function stableTransfersFromReceipt(receipt){const byAddress=new Map(Object.entries(STABLES).map(([asset,meta])=>[meta.address.toLowerCase(),{asset,...meta}]));const rows=[];for(const log of receipt?.logs||[]){const meta=byAddress.get(String(log.address||'').toLowerCase());if(!meta||log.topics?.[0]?.toLowerCase()!==TRANSFER||!log.topics[1]||!log.topics[2])continue;rows.push({hash:receipt.transactionHash,from:topicAddress(log.topics[1]),to:topicAddress(log.topics[2]),value:Number(BigInt(log.data||'0x0'))/10**meta.decimals,asset:meta.asset,category:'erc20',contractAddress:log.address});}return rows;}
const investigationCache=new Map(),INVESTIGATION_CACHE_MS=30000;
async function investigateWallet(query){const data=await getTransfers(query),analysis=analyseWallet(query,data.transfers);return {queryType:'wallet',provider:data.provider,network:'Ethereum Mainnet',subject:{address:query},summary:analysis.summary,risk:{score:analysis.score,level:analysis.level,signals:analysis.signals},graph:graphForWallet(query,analysis.transfers),transfers:analysis.transfers.slice(0,100),updatedAt:new Date().toISOString()};}
async function investigateTransaction(query){
  if(!KEY)throw new Error('Transaction-hash investigation requires a free Alchemy API key.');
  const [tx,receipt]=await Promise.all([rpc('eth_getTransactionByHash',[query]),rpc('eth_getTransactionReceipt',[query])]);if(!tx) return null;
  const block=tx.blockNumber?await rpc('eth_getBlockByNumber',[tx.blockNumber,false]):null,timestamp=block?parseInt(block.timestamp,16)*1000:null,value=Number(BigInt(tx.value||'0x0'))/1e18,stableTransfers=stableTransfersFromReceipt(receipt).map(transfer=>({...transfer,direction:transferDirection(tx.from,transfer),timestamp,blockNum:tx.blockNumber?parseInt(tx.blockNumber,16):null})),primary={hash:tx.hash,from:tx.from,to:tx.to,value,asset:'ETH',category:tx.input&&tx.input!=='0x'?'contract call':'external',direction:'outgoing',timestamp,blockNum:tx.blockNumber?parseInt(tx.blockNumber,16):null};
  let context={score:amountPoints('ETH',value),level:riskLevel(amountPoints('ETH',value)),signals:[],summary:{transferCount:1,incomingCount:0,outgoingCount:1,uniqueCounterparties:1,busiestWindowCount:1,totalsByAsset:{ETH:{incoming:0,outgoing:value}}},transfers:[primary]},riskScope='transaction';
  if(tx.from){try{const sender=await getTransfers(tx.from,true);context=analyseWallet(tx.from,sender.transfers);riskScope='sender_context';}catch{context.signals=[];}}
  if(!context.signals.length){const points=Math.max(amountPoints('ETH',value),...stableTransfers.map(t=>amountPoints(t.asset,t.value)));context.score=points;context.level=riskLevel(points);context.signals=[points?{key:'large_value',label:'Large-value transaction',points,detail:'This transaction crossed a configured review threshold.'}:{key:'transaction_context',label:'Transaction context',points:0,detail:'A single transaction does not provide enough evidence for a strong behavioral conclusion.'}];}
  const nodes=[{id:query,label:'Transaction',type:'transaction',side:'center'},{id:tx.from,label:'Sender',type:'wallet',address:tx.from,side:'incoming'}];if(tx.to)nodes.push({id:tx.to,label:'Recipient',type:'wallet',address:tx.to,side:'outgoing'});const edges=[{id:'sender',source:tx.from,target:query,label:'submitted',count:1}];if(tx.to)edges.push({id:'recipient',source:query,target:tx.to,label:`${value.toFixed(4)} ETH`,count:1});
  return {queryType:'transaction',provider:'Alchemy',network:'Ethereum Mainnet',subject:{hash:tx.hash,from:tx.from,to:tx.to,value,asset:'ETH',status:receipt?.status==='0x1'?'Confirmed':receipt?.status==='0x0'?'Failed':'Pending',blockNum:primary.blockNum,timestamp,gasUsed:receipt?.gasUsed?parseInt(receipt.gasUsed,16):null},summary:{...context.summary,tokenTransferCount:stableTransfers.length},risk:{score:context.score,level:context.level,scope:riskScope,evaluatedAddress:riskScope==='sender_context'?tx.from:null,signals:context.signals},graph:{nodes,edges,truncated:false,totalCounterparties:tx.to?2:1},transfers:[primary,...stableTransfers],updatedAt:new Date().toISOString()};
}
function assessPattern(e){
  const id=`${e.hash}:${e.asset}:${e.from}:${e.to}`;
  if(riskCache.has(id))return {...e,...riskCache.get(id)};
  const now=e.timestamp||Date.now(),cutoff=now-PATTERN_WINDOW,from=String(e.from||'').toLowerCase(),to=String(e.to||'').toLowerCase();
  const out=(walletActivity.get(from)?.out||[]).filter(x=>x.timestamp>=cutoff),incoming=(walletActivity.get(to)?.in||[]).filter(x=>x.timestamp>=cutoff);
  out.push(e);incoming.push(e);
  walletActivity.set(from,{out,in:(walletActivity.get(from)?.in||[]).filter(x=>x.timestamp>=cutoff)});
  walletActivity.set(to,{out:(walletActivity.get(to)?.out||[]).filter(x=>x.timestamp>=cutoff),in:incoming});
  const recipients=new Set(out.map(x=>String(x.to||'').toLowerCase())).size,sources=new Set(incoming.map(x=>String(x.from||'').toLowerCase())).size,total=out.length+incoming.length;
  const rapid=total>=3,burst=total>=6,fanOut=out.length>=3&&recipients>=3,fanIn=incoming.length>=3&&sources>=3;
  const amountScore=e.asset==='ETH'?(e.value>=100?25:e.value>=50?20:12):(e.value>=100000?25:e.value>=50000?20:12);
  let riskScore=amountScore,flaggedWallet=null;
  const signals=[`Large ${e.asset} transfer (+${amountScore})`];
  if(rapid){riskScore+=18;flaggedWallet=e.from;signals.push(`rapid movement: ${total} transfers / 10 min (+18)`);}
  if(burst){riskScore+=12;flaggedWallet=e.from;signals.push(`sustained burst (+12)`);}
  if(fanOut){riskScore+=22;flaggedWallet=e.from;signals.push(`fan-out to ${recipients} wallets (+22)`);}
  if(fanIn){riskScore+=18;flaggedWallet=e.to;signals.push(`fan-in from ${sources} wallets (+18)`);}
  if(recipients>=5){riskScore+=10;flaggedWallet=e.from;signals.push(`wide recipient spread (+10)`);}
  if(sources>=5){riskScore+=8;flaggedWallet=e.to;signals.push(`wide source spread (+8)`);}
  if(fanOut&&fanIn&&burst){riskScore+=15;signals.push(`compounded flow pattern (+15)`);}
  riskScore=Math.min(99,riskScore);
  const riskLevel=riskScore>=90?'CRITICAL':riskScore>=75?'HIGH':riskScore>=50?'MEDIUM':'LOW';
  const reason=`${riskLevel}: ${signals.join(' · ')}.`;
  const risk={riskScore,riskLevel,reason,flaggedWallet};riskCache.set(id,risk);return {...e,...risk};
}
async function globalFeed(){const block=await rpc('eth_getBlockByNumber',['latest',true]),events=[];for(const tx of block.transactions||[]){const value=Number(BigInt(tx.value||'0x0'))/1e18;if(value>=10)events.push({hash:tx.hash,from:tx.from,to:tx.to,value,asset:'ETH',blockNum:parseInt(block.number,16),timestamp:Number(parseInt(block.timestamp,16))*1000});}for(const [asset,meta] of Object.entries(STABLES)){const logs=await rpc('eth_getLogs',[{fromBlock:block.number,toBlock:block.number,address:meta.address,topics:[TRANSFER]}]);for(const log of logs||[]){if(!log.topics?.[1]||!log.topics?.[2])continue;const value=Number(BigInt(log.data||'0x0'))/10**meta.decimals;if(value>=10000)events.push({hash:log.transactionHash,from:topicAddress(log.topics[1]),to:topicAddress(log.topics[2]),value,asset,blockNum:parseInt(block.number,16),timestamp:Number(parseInt(block.timestamp,16))*1000});}}return events.slice(0,50).map(assessPattern);}
function address(q){return (q.query.address||'').trim();}function valid(a){return /^0x[a-fA-F0-9]{40}$/.test(a);}
app.get('/api/health',(q,s)=>s.json({ok:true,configured:!!KEY,monitoringReady:!!KEY,network:NETWORK,provider:KEY?'Alchemy':'Blockscout fallback',emailConfigured:smtpConfigured()}));
app.get('/api/price',async(q,s)=>{try{const d=await request('https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies=usd&include_24hr_change=true');s.json({usd:d.ethereum.usd,change24h:d.ethereum.usd_24h_change||0});}catch(e){s.status(502).json({error:e.message});}});
app.get('/api/transfers',async(q,s)=>{const a=address(q);if(!valid(a))return s.status(400).json({error:'Invalid Ethereum address.'});try{const d=await getTransfers(a);s.json({address:a,network:'eth-mainnet',provider:d.provider,count:d.transfers.length,transfers:d.transfers});}catch(e){s.status(502).json({error:e.message});}});
app.get('/api/investigate',async(q,s)=>{const query=String(q.query.query||'').trim(),isWallet=valid(query),isTransaction=/^0x[a-fA-F0-9]{64}$/.test(query);if(!isWallet&&!isTransaction)return s.status(400).json({error:'Enter a complete Ethereum wallet address or transaction hash.'});const key=query.toLowerCase(),cached=investigationCache.get(key);if(cached&&Date.now()-cached.at<INVESTIGATION_CACHE_MS)return s.json({...cached.data,cached:true});try{const data=isWallet?await investigateWallet(query):await investigateTransaction(query);if(!data)return s.status(404).json({error:'Transaction was not found on Ethereum Mainnet.'});investigationCache.set(key,{at:Date.now(),data});s.json(data);}catch(e){s.status(502).json({error:e.message});}});
app.get('/api/scan',async(q,s)=>{const a=address(q);if(!valid(a))return s.status(400).json({error:'Invalid Ethereum address.'});if(!KEY)return s.status(503).json({error:'Live monitoring requires a free Alchemy API key. Add ALCHEMY_API_KEY to .env.'});try{const d=await getTransfers(a,true),suspicious=d.transfers.map(t=>({...t,...scoreTransfer(t)})).filter(t=>t.riskScore>=70);s.json({address:a,provider:d.provider,recent:d.transfers.slice(0,10),suspiciousCount:suspicious.length,suspicious:suspicious.slice(0,10)});}catch(e){s.status(502).json({error:e.message});}});
app.get('/api/global-feed',async(q,s)=>{if(!KEY)return s.status(503).json({error:'Global feed requires a free Alchemy API key.'});try{s.json({provider:'Alchemy',events:await globalFeed()});}catch(e){s.status(502).json({error:e.message});}});
app.post('/api/email-alert',async(q,s)=>{const {address,alert}=q.body||{};if(!address||!alert)return s.status(400).json({error:'Missing alert details.'});if(!smtpConfigured())return s.status(503).json({sent:false,error:'Email is not configured. Add SMTP settings to .env.'});try{await mailer().sendMail({from:process.env.SMTP_FROM||process.env.SMTP_USER,to:process.env.ALERT_EMAIL_TO,subject:`🚨 ChainTrace — Suspicious activity (${alert.riskScore}/100)`,text:`Wallet: ${address}\nRisk: ${alert.riskScore}/100\nReason: ${alert.reason}\nAmount: ${alert.value||0} ${alert.asset||'ETH'}\nTransaction: ${alert.hash||'Unknown'}`});s.json({sent:true,to:process.env.ALERT_EMAIL_TO});}catch(e){s.status(502).json({sent:false,error:e.message});}});
app.listen(PORT,()=>console.log(`ChainTrace: http://localhost:${PORT}`));
